# Generated by Django 2.2.1 on 2019-06-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'permissions': (('ADD_ITEM', 'add item'), ('REMOVE_ITEM', 'delete item'), ('EDIT_ITEM', 'update item'), ('ADD_MANAGER', 'add manager'), ('REMOVE_STORE', 'delete store'), ('ADD_DISCOUNT', 'add discount'), ('ADD_RULE', 'add rule'))},
        ),
    ]
