# Generated by Django 2.2.2 on 2019-06-04 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='store',
            name='discount',
        ),
        migrations.AddField(
            model_name='store',
            name='managers',
            field=models.ManyToManyField(related_name='store_managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MaxMinCondition',
            fields=[
                ('condition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.Condition')),
                ('max_amount', models.PositiveIntegerField(default=2147483647)),
                ('min_amount', models.PositiveIntegerField(default=0)),
            ],
            bases=('store.condition',),
        ),
        migrations.CreateModel(
            name='ItemRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MXQ', 'max_quantity'), ('MNQ', 'min_quantity')], max_length=3)),
                ('parameter', models.CharField(max_length=120)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(help_text='format: mm/dd/yyyy')),
                ('percentage', models.PositiveSmallIntegerField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Condition')),
            ],
        ),
        migrations.CreateModel(
            name='BaseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MXQ', 'max_quantity'), ('MNQ', 'min_quantity'), ('RGO', 'registered_only'), ('FBC', 'forbidden_countries')], max_length=3)),
                ('parameter', models.CharField(max_length=120)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='discounts',
            field=models.ManyToManyField(to='store.Discount'),
        ),
        migrations.AddField(
            model_name='store',
            name='discounts',
            field=models.ManyToManyField(to='store.Discount'),
        ),
    ]
