# Generated by Django 2.2 on 2019-05-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('store', '0001_initial'),
	]

	operations = [
		migrations.RemoveField(
			model_name='store',
			name='id',
		),
		migrations.AlterField(
			model_name='store',
			name='name',
			field=models.CharField(max_length=30, primary_key=True, serialize=False),
		),
	]
