# Generated by Django 2.2 on 2019-05-01 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190501_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
