# Generated by Django 2.2.2 on 2019-06-18 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_auto_20190618_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagersWhoWait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approve', models.BooleanField(default=False)),
                ('user_who_wait', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='partners',
            field=models.ManyToManyField(related_name='store_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WaitToAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managers_who_wait', models.ManyToManyField(related_name='store_managers_to_wait', to='store.ManagersWhoWait')),
                ('store', models.ForeignKey(on_delete=None, to='store.Store')),
                ('user_to_wait', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
