# Generated by Django 2.2 on 2019-04-29 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='itemId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='store',
            name='items',
            field=models.ManyToManyField(to='store.Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='f', max_length=30),
        ),
    ]
