# Generated by Django 2.2 on 2019-05-01 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_remove_store_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='store_id',
            new_name='storeId',
        ),
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
