# Generated by Django 2.2 on 2019-05-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190501_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='storeId',
        ),
        migrations.AddField(
            model_name='store',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
