# Generated by Django 2.2.1 on 2019-05-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='description',
        ),
    ]
