# Generated by Django 2.2.1 on 2019-05-05 08:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading_system', '0002_remove_cart_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('customer', 'store')},
        ),
    ]
