# Generated by Django 2.2.1 on 2019-05-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_system', '0003_auto_20190505_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='items',
        ),
    ]
