# Generated by Django 2.2.1 on 2019-05-11 13:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading_system', '0005_auto_20190511_1539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auctionparticipant',
            unique_together={('auction', 'customer')},
        ),
    ]
